version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
     - "8000:80"
    depends_on:
      - app
    container_name: nginx

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
    - ./:/var/www
    depends_on:
      - db
    container_name: laravel-app

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel-meh
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql
